import numpy a np 

In [9]:
import numpy as np 
# column : [Temmp,Humadity,light]
reading = np.array([
    [75,60,380],
    [76, 63,380],
    [79,89,340],
    [78,89,350]

])
print(reading.shape)
# a 1d array for the collaboration 
calibrations = np.array([-2,-5,-10])
print(calibrations.shape)

new_add = reading + calibrations

print(new_add)



(4, 3)
(3,)
[[ 73  55 370]
 [ 74  58 370]
 [ 77  84 330]
 [ 76  84 340]]


In [10]:
from scipy import stats


transpose date to t

In [11]:
reading = np.array([
    [75,60,380],
    [76, 63,380],
    [79,89,340],
    [78,89,350]])

updated = reading.T
print(updated)

[[ 75  76  79  78]
 [ 60  63  89  89]
 [380 380 340 350]]


Sum of Squares Calculation with Time Measurement¶
calculate the sum of squares of all integers from 1 to n:

List-based approach: Using a list of integers and a for-loop to compute the sum of squares.
NumPy-based approach: Using NumPy's vectorized operations for a more efficient computation.
Both approaches measure the time taken for the operation and print the results.

In [12]:
def sum_of_squares_list(n):
    total  = 0
    for i in range(1 , n+1):
        total += i*i
    return total
print(sum_of_squares_list(5))

55


### Problem Description
Implement two functions to compare the memory usage of a Python list and a NumPy array, both containing integers from 0 to n-1 (1 ≤ n ≤ 10,000):

List-based approach:

Create a Python list of integers from 0 to n-1. Use sys.getsizeof() to calculate the memory of the list container and each element. Print and return the total memory used.
NumPy-based approach:

Create a NumPy array of integers from 0 to n-1. Use .nbytes to calculate the memory of the array’s elements. Print and return the total memory used.

Function Signatures:

memory_usage_list(n)

memory_usage_numpy(n)


Notes
Python List: Sum the memory of the list container and each element using sys.getsizeof().

NumPy Array: Use .nbytes to measure the memory of the array’s elements.

In [13]:
import sys
def memory_usage_list(n):
    list_num = []

    for i in range (1, n- 1):
        list_num.append(i)
    
    size_taken = sys.getsizeof(list_num)
    print(f"size taken by the list:",size_taken,"bytes")

    return list_num
print(memory_usage_list(5))



size taken by the list: 88 bytes
[1, 2, 3]


#### using numpy 


In [14]:
def memory_usage_numpy(n):
    numbers = np.arange(1, n-1)
    mem_taken = numbers.nbytes
    print(mem_taken)
    return numbers
    
print(memory_usage_numpy(5)) 

12
[1 2 3]


Problem Description
You are tasked with calculating the median of a given list of test scores using NumPy. The median is the middle value of the data when sorted in order. If there is an even number of values, the median is the average of the two middle values.

Your task is to implement a function that calculates the median of the scores using the NumPy library.


Function Signature:

calculate_median(scores)

Where:

scores is a list or NumPy array containing the test scores of students.
The function should return the median value of the scores.


Notes
You must use NumPy to calculate the median of the input list.

The function should handle any list of numerical values passed to it.

In case of an even number of elements, return the average of the two middle values.

In [15]:
def calculate_median(scores):
    

SyntaxError: incomplete input (3326263822.py, line 2)

### """" Problem Description
You are tasked with calculating the mode of a given list of test scores using NumPy and SciPy. The mode is the most frequently occurring value(s) in the data. If there are multiple values with the same highest frequency, the mode will return all of them.

Your task is to implement a function that calculates the mode of the scores using the SciPy library in combination with NumPy.

About SciPy: SciPy is a Python library used for scientific and technical computing. It builds on NumPy and provides additional functionality. In this problem, we will use scipy.stats.mode() to efficiently calculate the mode of a dataset.


Function Signature:

calculate_mode(scores)

Where:

scores is a list or NumPy array containing the test scores of students.
The function should return the mode(s) of the scores.


Notes
You must use SciPy’s stats.mode() function to calculate the mode of the input list.

The function should return the most frequent value(s).

In case there are multiple modes (a tie in frequency), return all the modes in ascending order.



In [ ]:
import numpy as np
from scipy import stats

def calculate_mode(scores):
    scores = np.array(scores)
    
    expected_mode = stats.mode(scores, keepdims=True)

    return expected_mode.mode[0]

| Module              | Purpose               |
| ------------------- | --------------------- |
| `scipy.optimize`    | Optimization          |
| `scipy.stats`       | Statistics            |
| `scipy.linalg`      | Linear Algebra        |
| `scipy.integrate`   | Integration           |
| `scipy.interpolate` | Interpolation         |
| `scipy.signal`      | Signal Processing     |
| `scipy.spatial`     | Distance calculations |
| `scipy.sparse`      | Sparse matrices       |
| `scipy.ndimage`     | Image processing      |


| NumPy                | SciPy                     |
| -------------------- | ------------------------- |
| Arrays               | Advanced algorithms       |
| Matrix operations    | Optimization              |
| Random numbers       | Statistics                |
| Broadcasting         | Integration               |
| Basic linear algebra | Signal & image processing |


Problem Description
A food delivery company wants to analyze delivery times based on past orders. To assess the trend, performance and improve operations.

Implement a function analyze_delivery_data(delivery_times) that:

Accepts:

delivery_times is a list of integers representing delivery times in minutes.
Returns:

The correct statistical measure (mean, median, or mode).
Uses:

NumPy and SciPy to compute the required statistics.

In [ ]:
import numpy as np
from scipy import stats

def analyze_delivery_data(delivery_times):
    delivery_times = np.array(delivery_times)
    expected_output = np.mean(delivery_times)
    return expected_output

Warehouse Inventory Management Stub
This notebook provides the structure for managing warehouse inventory across four warehouses: Central, North, South, and West.

You need to implement the logic in the update_inventory function, which updates the inventory by either adding new shipments or subtracting shipped-out products based on the add flag.

The helper function print_inventory is already implemented to display the inventory in a readable format. The test cells below will verify the correctness of your implementation.

Implement the update_inventory Function
This function should update the inventory for all four warehouses by applying the provided updates. Replace the pass statement with your implementation.

In [ ]:
def update_inventory(central_warehouse, north_warehouse, south_warehouse, west_warehouse, updates, add=True):
    central = np.array(central_warehouse)
    north = np.array(north_warehouse)
    south = np.array(south_warehouse)
    west = np.array(west_warehouse)
    if add:
        add_central = central + np.array(updates[0])
        add_north =  north + np.array(updates[1])
        add_south = south + np.array(updates[2])
        add_west = west + np.array(updates[3])
    else:#removing from the ware house 
        rem_central = central - np.array(updates[0])
        
        rem_north = north - np.array(updates[1])
        
        rem_south = south - np.array(updates[2])
        
        rem_west = west  - np.array(updates[3])

    return (
        central.tolist(),
        north.tolist(),
        south.tolist(),
        west.tolist()
    )
    



## using numpy 2d 

You are tasked with managing inventory for a set of products across four different warehouses: Central, North, South, and West. Each warehouse holds quantities of various products, and you need to update these quantities when:

New shipments are received at each warehouse.

Products are shipped out from the warehouses.

Instead of tracking inventory using lists, which can become slow and inefficient as more products are added, you will use NumPy 2D arrays for faster and more efficient updates.

You need to implement the following tasks:

Task 1: Update Inventory with New Shipments
You are given an initial inventory for each product across the four warehouses. When new shipments arrive at each warehouse, you will update the quantities accordingly.


Task 2: Update Inventory After Shipping Out Products
When products are shipped out from each warehouse, the inventory quantities must be reduced accordingly.


Task 3: Display the Current Inventory
After updating the inventory, display the updated quantities for each product in each warehouse in a structured format.


Task 4: Display Function
To visualize the updates, implement a function to display the updated inventory from the NumPy 2D array.


print_inventory_2d(inventory_matrix, header)

This function will print the product quantities in all warehouses with a given header.


Function Signature

update_inventory(inventory_matrix, updates, add=True)

Where:

inventory_matrix: A NumPy 2D array representing the quantities of each product in the four warehouses.

updates: A NumPy 2D array representing the quantities to be added or subtracted for each product in each warehouse.

add: A boolean value. If True, the function should add the updates to the inventory_matrix. If False, it should subtract the updates (for shipped-out products).

The function should return the updated NumPy 2D array after applying the updates.


Notes:
The inventory matrix is represented as a NumPy 2D array, where each row corresponds to a product, and each column corresponds to a warehouse.

Updates are provided as a NumPy 2D array with the same dimensions as the inventory matrix.

Use the add parameter to decide whether to add or subtract the updates from the inventory matrix.


Checklist

Approach Level 1:


Approach Level 2:

In [ ]:
import numpy as np

def update_inventory(warehouses, updates, add=True):

    warehouses = np.array(warehouses)
    updates = np.array(updates)

    if add:
        updated = warehouses + updates
    else:
        updated = warehouses - updates

    return updated.tolist()

Concept Recap
Matrix transposition involves swapping rows and columns in a matrix. This operation is useful when you need to reorganize data for easier comparison across different dimensions (e.g., products vs. months). By transposing, you change the perspective from rows to columns.

Example: Given a matrix:

Product	Jan	Feb	Mar
Smartphone	200	180	220
Laptop	150	170	160
Headphones	300	320	310
Transposing it gives:

Month	Smartphone	Laptop	Headphones
Jan	200	150	300
Feb	180	170	320
Mar	220	160	310

Problem Description
You are given a 2D list sales_matrix where each row represents a product and each column represents a month. Implement the function transpose_sales_data() that:

Accepts a 2D list of sales data.

Transposes the matrix (switch rows with columns).

Returns the transposed matrix.


Function Signature:

def transpose_sales_data(sales_matrix):


Notes
The input matrix will always be valid with at least one row and column.

Sample Input:

sales_matrix = [

  [200, 180, 220],

  [150, 170, 160],

  [300, 320, 310]

]

Sample Output:

[[200, 150, 300],

[180, 170, 320],

[220, 160, 310]]


Explanation:
After transposition, each column corresponds to a product's sales data for different months.



Checklist

Approach Level 1:


Approach Level 2:

arr.shape        # (rows, columns)
arr.ndim         # number of dimensions
arr.size         # total elements
arr.dtype        # data type
arr.T            # transpose
arr.sum()        # sum of all elements
arr.mean()       # average
arr.max()        # maximum
arr.min()        # minimum
arr.flatten()    # convert to 1D

In [ ]:
import numpy as np

def transpose_sales_data(sales_matrix):
    sales = np.array(sales_matrix)
    expected_output = sales.T
    return expected_output.tolist()

In [ ]:
sales_matrix = [[200, 180, 220],
                [150, 170, 160],
                [300, 320, 310]]

expected_output = [[200, 150, 300],
                   [180, 170, 320],
                   [220, 160, 310]]

try:
    output = transpose_sales_data(sales_matrix)
    assert output == expected_output, f"Expected {expected_output}, but got {output}"
    print('✅ Test Passed: Transpose function works correctly.')
except Exception as e:
    print(f'❌ Test Failed: {e}')

✅ Test Passed: Transpose function works correctly.


Concept Recap
The dot product (also known as the scalar product) is a mathematical operation that takes two equal-length sequences of numbers and returns a single number. It is calculated as the sum of the products of the corresponding elements in both sequences.

For example, given two lists:

A = [1, 2, 3]

B = [4, 5, 6]

The dot product is computed as:

(1×4) + (2×5) + (3×6) = 4 + 10 + 18 = 32

This concept is widely used in vector algebra, physics, and finance.


Use Case
A portfolio manager needs to calculate the overall return of a portfolio. Each stock in the portfolio has a return percentage and a weight (percentage of the total portfolio). The portfolio return is determined using the dot product of these two lists.


Problem Description
Implement a function portfolio_return that:

Accepts two lists of integers:

returns: A list where each element represents the return percentage of a stock.

weights: A list where each element represents the weight (percentage) of the corresponding stock.

Computes the overall portfolio return using the dot product of these two lists.

Returns the result as a floating-point number.

Function signature:
import numpy as np

def portfolio_return(returns, weights):

Notes
Both lists returns and weights will have the same length.

The weights list contains percentage values (e.g., 50 means 50%).

Convert weights to decimal form before calculating the dot product.

Use numpy.dot() to compute the weighted sum.


Sample Inputs and Outputs
Sample Input 1:

returns = [10, 5, 8]

weights = [50, 30, 20]

Sample Output 1:

8.1

Explanation:

(10×0.50) + (5×0.30) + (8×0.20) = 5 + 1.5 + 1.6 = 8.1%


Sample Input 2:

returns = [12, 7, 15, 5]

weights = [40, 20, 30, 10]

Sample Output 2:

10.4

Explanation:

(12×0.40) + (7×0.20) + (15×0.30) + (5×0.10) = 4.8 + 1.4 + 4.5 + 0.5 = 10.4%



In [ ]:
import numpy as np

def portfolio_return(returns, weights):
    """
    Computes the overall portfolio return using the dot product.

    Parameters:
    returns (list): List of return percentages for each stock.
    weights (list): List of weight percentages for each stock (should sum to 100).

    Returns:
    float: The overall portfolio return as a weighted average.
    
    """
    returns = np.array(returns)
    weights = np.array(weights)
    weights = weights / 100
    expected_output = np.dot(weights,returns)
    
    return expected_output
    
    # TODO

In [ ]:
# Test: Calculating portfolio return
returns = [10, 5, 8]
weights = [50, 30, 20]
expected_output = 8.1

try:
    output = portfolio_return(returns, weights)
    assert round(output, 2) == round(expected_output, 2), f"Expected {expected_output}, but got {output}"
    print("✅ Test Passed: Portfolio return function works correctly.")
except Exception as e:
    print(f"❌ Test Failed: {e}")

✅ Test Passed: Portfolio return function works correctly.


Concept Recap
Scalar multiplication refers to the process of multiplying each element of a matrix by a scalar (a constant value). In practical applications, this can be used to apply uniform adjustments, such as increasing all salaries in a matrix by a fixed percentage. In NumPy, scalar multiplication is straightforward and efficient.

Example:
Given a matrix A = [[1, 2], [3, 4]] and a scalar k = 2, scalar multiplication results in:


k * A = [[2, 4], [6, 8]]


Problem Description
You are an HR manager at a company and need to apply a 10% salary increase to all employees across different departments. You will do this by performing matrix scalar multiplication using NumPy.

Implement a function apply_salary_increase(salary_matrix, scalar) that:

Accepts a 2D NumPy array salary_matrix representing current salaries of employees across various departments.

Accepts a scalar scalar which will be used to apply the percentage increase (e.g., 1.10 for a 10% increase).

Returns a new matrix where each salary has been multiplied by the scalar rounded to two decimal places to reflect the salary increase.

Use np.round(salary_matrix, 2) to roundoff.


Notes
The salary matrix will have 3 rows (departments) and 3 columns (employees in each department).

The scalar value will be a floating-point number.

Use NumPy for matrix manipulation.


Sample Input 1:

salary_matrix = np.array([

[40, 45, 50],

[55, 60, 50],

[70, 75, 80]

])


scalar = 1.10

Sample Output 1:

[[44.0, 49.5, 55.0],

[60.5, 66.0, 55.0],

[77.0, 82.5, 88.0]]

Explanation:
Each salary in the matrix is multiplied by 1.10, resulting in the new salaries for all employees.


Sample Input 2:

salary_matrix = np.array([

[100, 120, 130],

[150, 160, 140],

[200, 210, 220]

])


scalar = 1.05

Sample Output 2:

[[105.0, 126.0, 136.5],

[157.5, 168.0, 147.0],

[210.0, 220.5, 231.0]]

Explanation:
Each salary in the matrix is multiplied by 1.05, reflecting a 5% salary increase.

In [ ]:

def apply_salary_increase(salary_matrix, scalar):
    increased_salary = salary_matrix * scalar
    return np.round(increased_salary, 2)

In [ ]:
# Test: Applying salary increase
salary_matrix = np.array([
    [40, 45, 50],
    [55, 60, 50],
    [70, 75, 80]
])

scalar = 1.10

expected_salary_output = np.array([
    [44.0, 49.5, 55.0],
    [60.5, 66.0, 55.0],
    [77.0, 82.5, 88.0]
])

try:
    salary_output = apply_salary_increase(salary_matrix, scalar)
    assert np.array_equal(salary_output, expected_salary_output), f"Expected:\n{expected_salary_output}\nBut got:\n{salary_output}"
    print('✅ Test Passed: Salary increase function works correctly.')
except Exception as e:
    print(f'❌ Test Failed: {e}')

✅ Test Passed: Salary increase function works correctly.


Use Case
An e-commerce platform needs to perform price analysis for products in a specific category. However, some of the product prices are missing (represented by NaN values). The platform wants to compute the average price (mean), the median price, and the most common price (mode), excluding the missing values.


Problem Description
Implement a function analyze_prices(prices) that:

Accepts a list of product prices, some of which may be NaN.

Calculates the mean, median, and mode of the prices, excluding the NaN values.

Returns a dictionary containing the mean, median, and mode values, in that order.


Function Signature:

def analyze_prices(prices)


Notes
You can assume the list prices will contain at least one non-NaN value.

If all values in the list are NaN, the function should return the values as None.


Sample Input 1:

In [ ]:
import numpy as np
from scipy import stats

def analyze_prices(prices):
    prices = np.array(prices, dtype=float)

    # Remove NaN values
    prices = prices[~np.isnan(prices)]

    # If no valid values remain
    if prices.size == 0:
        return {
            "mean": None,
            "median": None,
            "mode": None
        }

    mean = np.mean(prices)
    median = np.median(prices)
    mode = stats.mode(prices, keepdims=True).mode[0]

    return {
        "mean": mean,
        "median": median,
        "mode": mode
    }

    prices = prices[~np.isnan(prices)]
How It Works Step-by-Stepnp.isnan(prices): Creates a boolean array (Mask 1) checking each element. It returns True where a value is NaN and False where it is a valid number.
~: This is the logical NOT operator. It flips all the boolean values in Mask 
1. True becomes False (hiding the NaNs), and False becomes True (keeping the valid numbers).
prices[...]: This indexes the original array using the flipped mask. NumPy keeps only the elements that align with a True value.Visual Example

In [ ]:
import numpy as np

# Test Sample Input 1
prices1 = [100, 150, 200, np.nan, 250, 150, np.nan, 300]
expected_output1 = {
    "mean": 191.66666666666666,  # Correct mean: (100 + 150 + 200 + 250 + 150 + 300) / 6
    "median": 175.0,
    "mode": 150.0
}

output1 = analyze_prices(prices1)
print("Output for Sample Input 1:", output1)

# Validate the results for Sample Input 1
assert np.isclose(output1["mean"], expected_output1["mean"]), f"Expected mean {expected_output1['mean']}, got {output1['mean']}"
assert np.isclose(output1["median"], expected_output1["median"]), f"Expected median {expected_output1['median']}, got {output1['median']}"
assert output1["mode"] == expected_output1["mode"], f"Expected mode {expected_output1['mode']}, got {output1['mode']}"
print("✅ Test Passed for Sample Input 1")

# Test Sample Input 2 (all values are NaN)
prices2 = [np.nan, np.nan, np.nan]
expected_output2 = {
    "mean": None,
    "median": None,
    "mode": None
}

output2 = analyze_prices(prices2)
print("\nOutput for Sample Input 2:", output2)
assert output2 == expected_output2, f"Expected {expected_output2}, got {output2}"
print("✅ Test Passed for Sample Input 2")

Output for Sample Input 1: {'mean': 191.66666666666666, 'median': 175.0, 'mode': 150.0}
✅ Test Passed for Sample Input 1

Output for Sample Input 2: {'mean': None, 'median': None, 'mode': None}
✅ Test Passed for Sample Input 2


Concept Recap
In statistics, measures of central tendency (mean, median, and mode) summarize a dataset with a single representative value.

Mean: The sum of all values divided by the number of values.

Median: The middle value in a sorted list of numbers. If there is an even number of values, it’s the average of the two middle ones.

Mode: The most frequent value in the dataset.

Outliers (extreme values) can distort the mean, making it less representative. The median is more robust to outliers.


Problem Description
A real estate analyst needs to find the typical home price in a neighborhood, but the dataset includes unusually high prices that might skew the result.

Write a function find_central_tendency(prices) that:

Returns the mean if there are no outliers (prices ≤ $1,000,000).

Returns the median if there are outliers (any price > $1,000,000).

Returns the mode if all values are identical.

If all values are unique, return None for mode.

Outlier Detection:
Consider a price above $1,000,000 as an outlier.

If outliers are present, always return the median.

If no outliers, return the mean unless all values are identical.

In [ ]:
import numpy as np
from scipy import stats

def find_central_tendency(prices):
    prices = np.array(prices)

    if np.all(prices == prices[0]):
        result = stats.mode(prices, keepdims=True).mode[0]
        

    elif np.any(prices > 1_000_000):
        result = np.median(prices)

    else:
        result = np.mean(prices)

    return 
  

In [ ]:
# Test: Checking the function with a dataset containing outliers
prices = [200000, 250000, 300000, 1000000, 1200000]
expected_output = "Median: 300000"

try:
    result = find_central_tendency(prices)
    assert result == expected_output, f"Expected {expected_output}, but got {result}"
    print("✅ Test Passed: Correct median calculated for dataset with outliers.")
except Exception as e:
    print(f"❌ Test Failed: {e}")

❌ Test Failed: Expected Median: 300000, but got 300000


Similar Interview Questions

These questions test the same concepts.

1. Student Marks

If any mark is negative, return the median; otherwise, return the mean.

2. Employee Salaries

If any salary is above ₹1 crore, return the median salary; otherwise, return the average salary.

3. Daily Temperature

If any temperature is above 50°C, return the median temperature; otherwise, return the mean.

4. Website Response Time

If any response time exceeds 5000 ms, use the median because outliers distort the average.

5. Stock Prices

If any day's price is more than 3× the average, report the median; otherwise, report the mean.

6. Cricket Scores

If all players scored the same runs, return the mode; otherwise, return the mean.

7. Product Ratings

Given ratings with missing values (None or np.nan), compute the average while ignoring missing values.

8. Hospital Wait Times

If an extreme wait time (outlier) exists, use the median to represent the typical waiting time.

Interview Tips

For these kinds of questions, identify the required operations first:

Requirement	Python Function
Average	mean() or sum()/len()
Middle value	median()
Most frequent value	mode()
Outlier check	any(value > threshold for value in data)
All values identical	len(set(data)) == 1
Sort values	sorted(data)

The biggest mistake candidates make is computing the mean first without checking the conditions. Always follow the decision rules in the order given by the problem statement.

Problem Description
The city traffic department wants to determine the busiest intersection based on traffic data collected over multiple time intervals. This helps in optimizing traffic management and infrastructure planning.

Implement the function find_busiest_intersection(traffic_data), which:

Accepts a 2D NumPy array traffic_data, where each row represents an intersection and each column represents traffic count at different times.

Computes the total traffic at each intersection.

Returns the index of the intersection with the highest total traffic.


Notes
If multiple intersections have the same total traffic, return the smallest index.

The input is guaranteed to have at least one intersection.

In [ ]:
import numpy as np

def find_busiest_intersection_numpy(traffic_data):
    traffic_data = np.array(traffic_data)
    total_traffic = np.sum(traffic_data, axis=1)
    return np.argmax(total_traffic)


In [ ]:
def find_busiest_intersection_list(traffic_data):
    totals = [sum(row) for row in traffic_data]
    return totals.index(max(totals))    #TODO

In [ ]:
traffic_data =([
    [200, 180, 220],  
    [150, 170, 190],  
    [300, 310, 290]  
])

expected_output = 2  # Intersection 2 has the highest total traffic

try:
    # Test with NumPy method
    result_numpy = find_busiest_intersection_numpy(traffic_data)
    assert result_numpy == expected_output, f"Expected {expected_output}, but got {result_numpy}"
    
    # Test with list-based method
    result_list = find_busiest_intersection_list(traffic_data)
    assert result_list == expected_output, f"Expected {expected_output}, but got {result_list}"
    
    print('✅ Test Passed: Busiest intersection found correctly.')
except Exception as e:
    print(f'❌ Test Failed: {e}')

Problem Description
A movie recommendation system needs to estimate a missing movie rating for a user based on available ratings using basic matrix operations.

Implement a function predict_rating(ratings, user_index, movie_index) that:

Accepts a ratings matrix where each row represents a user and each column represents a movie's rating. Missing ratings are represented as np.nan.

Takes user_index, representing the target user.

Takes movie_index, representing the target movie.

Returns the predicted rating using the average rating of other users who have rated the movie.


Notes
If no other users have rated the movie, return np.nan.

Use NumPy functions for efficient computation.

In [ ]:
import numpy as np

def predict_rating(ratings, user_index, movie_index):
    ratings = np.array(ratings, dtype=float)

    # Get all ratings for the movie
    movie_ratings = ratings[:, movie_index]

    # Remove the target user's rating
    other_ratings = np.delete(movie_ratings, user_index)

    # Keep only valid (non-NaN) ratings
    valid_ratings = other_ratings[~np.isnan(other_ratings)]

    # If no valid ratings exist, return NaN
    if len(valid_ratings) == 0:
        return np.nan

    # Return the average rating
    return np.mean(valid_ratings)

In [ ]:
import numpy as np

def predict_rating_numpy(ratings, user_index, movie_index):
    ratings = np.array(ratings, dtype=float)

    # Get ratings for the specified movie
    movie_ratings = ratings[:, movie_index]

    # Exclude the target user's rating
    movie_ratings = np.delete(movie_ratings, user_index)

    # If all remaining ratings are NaN, return NaN
    if np.all(np.isnan(movie_ratings)):
        return np.nan

    # Compute the average ignoring NaN values
    return np.nanmean(movie_ratings)

In [ ]:
def run_test_case(test_name, func, ratings, user_index, movie_index, expected):
    try:
        result = func(ratings, user_index, movie_index)
        assert np.isclose(result, expected, equal_nan=True), f"Expected {expected}, but got {result}"
        print(f"✅ {test_name} Passed")
    except AssertionError as e:
        print(f"❌ {test_name} Failed: {e}")

# Define sample ratings matrix for testing
ratings = np.array([
    [4, 5, np.nan],
    [2, 3, 5],
    [5, 5, 4]
])

# Sample Input 1: Predict rating for user 0 on movie 2
run_test_case("Basic Test - predict_rating", predict_rating, ratings, 0, 2, 4.5)
run_test_case("Basic Test - predict_rating_numpy", predict_rating_numpy, ratings, 0, 2, 4.5)

| Function                  | Purpose                                      |
| ------------------------- | -------------------------------------------- |
| `np.array()`              | Convert list to NumPy array                  |
| `ratings[:, movie_index]` | Get the selected movie's ratings (column)    |
| `np.delete()`             | Remove the target user's rating              |
| `np.isnan()`              | Check which values are `NaN`                 |
| `np.all()`                | Check if all values satisfy a condition      |
| `np.nanmean()`            | Compute the mean while ignoring `NaN` values |


Use Case
A sports coach wants to evaluate player performance based on multiple skill metrics to determine the best overall player.

Problem Description
Implement a function find_best_player(players) that:

Accepts a 2D NumPy array players, where each row represents a player and each column represents a skill metric.

Computes an overall performance score for each player.

Returns the index of the best-performing player.


Notes
Use NumPy operations such as dot product, arithmetic operations, and statistical functions where applicable.

The dataset may contain np.nan values, which should be ignored when computing scores.

In case of a tie, return the lowest index.

In [16]:
import numpy as np

def find_best_player(players):
    players = np.array(players, dtype=float)

    # Compute the average score for each player, ignoring NaN values
    scores = np.nanmean(players, axis=1)

    # If a player's row is all NaN, nanmean returns NaN.
    # Treat those players as having the lowest possible score.
    scores = np.nan_to_num(scores, nan=-np.inf)

    # Return the index of the highest score.
    # np.argmax returns the first occurrence in case of a tie.
    return np.argmax(scores)

Similar Interview Questions
1. Best Student
Marks

80 75 90
90 85 NaN
88 91 87

Return the student with the highest average.

Concepts: np.nanmean(axis=1), np.argmax()

2. Best Employee
Sales Quality Attendance

90 85 100
95 NaN 90
80 92 95

Find the employee with the highest performance.

3. Best Hospital
Patient Satisfaction

4
5
NaN

Find the hospital with the highest average rating.

4. Best Cricket Player
Runs Wickets Catches

80 2 1
65 5 2
100 NaN 0

Find the best all-rounder.

5. Movie Recommendation (very common)
Users

5 NaN 4
4 2 5
3 5 NaN

Predict the missing rating using the average of other users.

Concepts: np.delete(), np.nanmean()

6. Find the Busiest Intersection
Cars

100 120 150
200 180 170
90 100 80

Return the busiest intersection.

Concepts:

np.sum(axis=1)
np.argmax()
7. Best Salesperson
Jan Feb Mar

40 55 60
50 65 70
45 50 55

Find the highest total sales.

Concepts:

np.sum(axis=1)
np.argmax()
8. Most Popular Product
Store1
Store2
Store3

Find which product sold the most.

Concepts:

np.sum(axis=0)
np.argmax()
9. Best Stock
Daily Returns

2 4 5
3 2 7
5 1 3

Find the stock with the highest average return.

10. Weighted Performance (Very Common)

Each skill has a different importance.

weights = [0.4, 0.3, 0.3]

Compute

scores = np.dot(players, weights)

Return

np.argmax(scores)

This tests the dot product, which is widely used in machine learning for combining features with weights.

Common NumPy Interview Patterns

Many interview questions reduce to one of these patterns:

Pattern	NumPy Solution
Find row total	np.sum(arr, axis=1)
Find column total	np.sum(arr, axis=0)
Find row average	np.mean(arr, axis=1)
Ignore missing values	np.nanmean()
Highest row	np.argmax()
Lowest row	np.argmin()
Apply weights	np.dot(arr, weights)
Filter values	arr[arr > x]
Find indices meeting a condition	np.where(condition)

If you're preparing for ₹20–30 LPA Data Analyst, AI/ML, or Data Engineering interviews, mastering these patterns will help you solve a large number of NumPy coding questions quickly.