import numpy a np 

In [3]:
import numpy as np 
# column : [Temmp,Humadity,light]
reading = np.array([
    [75,60,380],
    [76, 63,380],
    [79,89,340],
    [78,89,350]

])
print(reading.shape)
# a 1d array for the collaboration 
calibrations = np.array([-2,-5,-10])
print(calibrations.shape)

new_add = reading + calibrations

print(new_add)



(4, 3)
(3,)
[[ 73  55 370]
 [ 74  58 370]
 [ 77  84 330]
 [ 76  84 340]]


In [ ]:
from scipy import stats
